### ISSUE TITLE
supplementary materials

### ISSUE THREAD

**Issue by xuheyang** [PointsCoder/VOTR#1]
Thank you for your amazing article.
But in released paper, I do not see the detailed design of attention mechanisms.
The article said: "We would like readers to refer to supplementary materials for the detailed design of attention mechanisms." But in your article, I do not find the "supplementary materials" part. Can you release supplementary materials? thank you very much.

**Comment by PointsCoder** [comment]
@xuheyang supp will be later released.
A direct way to learn the design of attention mechanism is to read the config files and CUDA code in votr_ops

**Comment by xuheyang** [comment]
Thank you very much! I will try it.
