### ISSUE TITLE
where is the empty voxel feature in sparse voxel module ?

### ISSUE THREAD

**Issue by xiaoyu0318** [PointsCoder/VOTR#14]
I don't know where the code of empty voxel feature, can you tell me pls?

**Comment by PointsCoder** [comment]
We perform sparse attention only when we downsample the voxel resolutions, and that means those downsampled voxels are at previous empty locations. You can refer to Fig.7 in the appendix for illustration.

The code of voxel downsampling and attention is at pcdet/ops/votr_ops/src/build_mapping_gpu.cu.

**Comment by PointsCoder** [comment]
Closed if no other issues
