### ISSUE TITLE
A question about the paper.

### ISSUE THREAD

**Issue by czy-0326** [PointsCoder/VOTR#15]
In the introduction in the paper,you write that ' the voxel size as (0.05m,0.05m,0.1m) on the KITTI dataset, the maximum receptive field in the last layer is only (3.65m,3.65m,7.3m)', Can you tell me why the receptive field expands the 73 times?

**Comment by PointsCoder** [comment]
@czy-0326 The paper cites the commonly used 3D backbone in the SECOND detector on KITTI.

The architecture of SECOND has 12 blocks of sparse and submanifold convolutions and downsample 8x. You can calculate the theoretical receptive field to obtain the reported results.

**Comment by PointsCoder** [comment]
Closed if no other queations.
