### ISSUE TITLE
Performance of this reproduced repo

### ISSUE THREAD

**Issue by weihaosky** [PointsCoder/VOTR#18]
Nice work for reproducing VOTR!
Since there are many details missing in the paper, how much is the reproduced version close to the original version? 
May I ask how is the performance of this reproduced version? Can it achieve the performance in the paper?  
Many thanks!

**Comment by PointsCoder** [comment]
All the performances can be reproduced as the reported numbers in the paper.

**Comment by weihaosky** [comment]
Great! Are the details the same as the paper? Or you just implement it according to your ideas. e.g., how to search for the attending pixels, the number of 'RANGE_SPEC', 'SIZE'.

**Comment by weihaosky** [comment]
So is this repo an official implementation of the paper?
