### ISSUE TITLE
building error because of lacking files

### ISSUE THREAD

**Issue by Niyiyang-learner** [PointsCoder/VOTR#2]
I try to run "python setup.py develop", but it failed.
I got
"**fatal error**: build_mapping_gpu.h: No such file or directory".
When I open the setup.py, I find that this repo lacks four files: 'build_mapping.cpp', 'build_mapping_gpu.cu', 'build_attention_indices.cpp' and 'build_attention_indices_gpu.cu'.
How can I get these files.
Thank you!

**Comment by PointsCoder** [comment]
@Niyiyang-learner Missing files have been added.

**Comment by Niyiyang-learner** [comment]
> @Niyiyang-learner Missing files have been added.

Thank you for your help!
