### ISSUE TITLE
RuntimeError. How to run it On Spconv2?

### ISSUE THREAD

**Issue by Raiden-cn** [PointsCoder/VOTR#25]
My GPU is RTX30 series.
I can't use CUDA10 so that I cant use Spconv1.2.

Although I try to transfer it to OpenPCDet that supports Spconv2 , there still are some question I cant fix it.

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2962, 64]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by jlqzzz** [comment]
> 
How did you solve this problem? I have the same problem.

Thank you!

**Comment by Raiden-cn** [comment]
@jlqzzz Hi! Sry, I can't detail it. Cuz I almost forgot all about it. :(
I suggest you change the version of pytorch.
Btw, my pytorch and cudatoolkit version is 1.8, 11.1 respectively.
If it doesn't work, you shuold debug the code line by line where the error appeared to find out why it happen.

**Comment by bueeciel9** [comment]
My setting is torch: 1.9 cuda: 11.1 cudnn8-devel, python: 3.7.11, but it doesn't work. Got the same issue.

Can you give me another solution for it, please?

**Comment by sfy-1739** [comment]
My setting is torch: 1.10 cuda: 11.3. Got the same issue.

How did you solve this problem? I have the same problem.

Thank you!

**Comment by bueeciel9** [comment]
The best way is download spconv 1.2.1 through docker. I tried lots of things, but already spconv1.x version is not provided, so just download it through docker.
