### ISSUE TITLE
Error when compile CUDA operators

### ISSUE THREAD

**Issue by ahaheng** [PointsCoder/VOTR#3]
Thanks for sharing your work.

I got some errors when I try to compile  votr_ops.

As shown below, the source list includes `build_mapping.cpp`, `build_mapping_gpu.cu`,`build_attention_indices.cpp` and `build_attention_indices_gpu.cu`. But these files cannot be found in the folder of `pcdet/ops/votr_ops/`.
https://github.com/PointsCoder/VOTR/blob/c44a21ccd9e126c7cbbbce804db95524af1f6f02/setup.py#L56-L64
Can you give me some advice? Thanks.

**Comment by PointsCoder** [comment]
@ahaheng Missing files have been added.

**Comment by ahaheng** [comment]
> @ahaheng Missing files have been added.

Thanks.
