### ISSUE TITLE
Model Performance

### ISSUE THREAD

**Issue by YoushaaMurhij** [PointsCoder/VOTR#6]
Nice work!
What is the latency  (inference speed) of this backbone? I can't find that in the paper.

**Comment by PointsCoder** [comment]
VoTr backbone+FPN+anchor head takes around 70ms on KITTI. I didn't test the single backbone results.

**Comment by YoushaaMurhij** [comment]
Could you please provide a simple inference code of your model that takes a point loud and returns the detected objects?
