### ISSUE TITLE
Multiple classes model & Inference 

### ISSUE THREAD

**Issue by YoushaaMurhij** [PointsCoder/VOTR#7]
Have tried to train a model with all Waymo classes (Vehicles, Pedestrians and Cyclists)? do you recommend me to try that? or there will be a potential drop in mAP.
Do you have a plan to add a simple inference code of your model that takes a point cloud and returns the detected objects?

Thanks!

**Comment by PointsCoder** [comment]
Hyperparameters are specially tuned for the vehicle/car class. I guess there may be a performance drop if you train with 3 classes.

For inferencing a single point cloud, you can replace the data loader according to your need in train.py.
